EAGLEVIEW_API_USERNAME: "<EAGLEVIEW_USERNAME>"
EAGLEVIEW_API_PASSWORD: "<EAGLEVIEW_PASSWORD>"
EAGLEVIEW_API_SOURCE_ID: "<EAGLEVIEW_SOURCE_ID>"
EAGLEVIEW_API_CLIENT_SECRET: "<EAGLEVIEW_API_CLIENT_SECRET>"